root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main main.go"
  bin = "tmp/main"
  include_ext = ["go", "tmpl", "tpl", "html"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
  stop_on_error = true

[log]
  time = true

[color]
  main = "yellow"
